apiVersion: v1
kind: Service
metadata:
  name: ing-reposition-it-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app: ing-reposition-it-api
