apiVersion: v1
kind: Service
metadata:
  name: ing-reposition-it-fe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 2001
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app: ing-reposition-it-ui
