client_id                        = ""
client_secret                    = ""
tenant_id                        = ""
subscription_id                  = ""
location                         = "southeastasia"
resource_group_name              = "ing-reposition-it-dev-rg"
resource_prefix                  = "ing-reposition-it"
