apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: nginx-ingress
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sgraza@palo-it.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
