client_id                        = ""
client_secret                    = ""
tenant_id                        = ""
subscription_id                  = ""
location                         = "southeastasia"
resource_group_name              = "ing-reposition-it"
resource_prefix                  = "ing-reposition-it"
vnet_cidr                        = "192.168.0.0/22"
